services:
  portfolio:
    image: ghcr.io/spitzerl/portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - nginx-proxy-manager_web_network

networks:
  nginx-proxy-manager_web_network:
    external: true
