services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio:local
    container_name: portfolio
    restart: unless-stopped
    healthcheck:
      disable: true
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - 'traefik.http.routers.portfolio.rule=Host(`lucasspitzer.fr`) || Host(`www.lucasspitzer.fr`)'
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
    networks:
      - proxy

networks:
  proxy:
    external: true
